# Generated by Django 2.2 on 2019-05-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={},
        ),
    ]
